# Generated by Django 4.1.11 on 2023-09-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='property_area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='property_cost',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='property_link',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='property_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='property_type',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
